export const lessonRegistry = [
  { id: "platform-guide", title: "0. Platform Guide & Role Overview", file: "/legacy/docs/sections/00g-platform-guide.md" },
  { id: "help-overview", title: "0.0 Help Overview", file: "/legacy/docs/sections/00-help-overview.md" },
  { id: "stability-checker-guide", title: "0.05 Stability Checker & Metrics Explained", file: "/legacy/docs/sections/00h-stability-checker-guide.md" },
  { id: "operating-modes", title: "0.06 Controller Operating Modes", file: "/legacy/docs/sections/00i-operating-modes.md" },
  { id: "toolbar-run-controls", title: "0.1 Toolbar and Run Controls", file: "/legacy/docs/sections/00a-toolbar-run-controls.md" },
  { id: "faceplate-operator-controls", title: "0.2 Faceplate and Operator Controls", file: "/legacy/docs/sections/00b-faceplate-operator-controls.md" },
  { id: "controller-settings", title: "0.3 Controller Settings Explained", file: "/legacy/docs/sections/00c-controller-settings-explained.md" },
  { id: "tuning-methods", title: "0.35 Standard Tuning Methods", file: "/legacy/docs/sections/00ca-standard-tuning-methods.md" },
  { id: "process-signals-trends", title: "0.4 Process, Signals, and Trend Tools", file: "/legacy/docs/sections/00d-process-signals-and-trend-tools.md" },
  { id: "training-exercises", title: "0.5 Operator Training Exercises", file: "/legacy/docs/sections/00e-operator-training-exercises.md" },
  { id: "process-model-library", title: "0.6 Process Model Library", file: "/legacy/docs/sections/00f-process-model-library.md" },
  { id: "executive-summary", title: "1. Executive Summary", file: "/legacy/docs/sections/01-executive-summary.md" },
  { id: "fundamentals", title: "2. PID Control Fundamentals", file: "/legacy/docs/sections/02-pid-control-fundamentals.md" },
  { id: "controller-selection", title: "3. Choosing the Right Controller", file: "/legacy/docs/sections/03-choosing-the-right-controller.md" },
  { id: "terminology-mapping", title: "4. PID Terminology Mapping", file: "/legacy/docs/sections/04-pid-terminology-mapping.md" },
  { id: "deadband-neutral-zone", title: "5. Deadband / Neutral Zone", file: "/legacy/docs/sections/05-deadband-neutral-zone.md" },
  { id: "bias-offset-manual-reset", title: "6. Bias, Offset, and Manual Reset", file: "/legacy/docs/sections/06-bias-offset-manual-reset.md" },
  { id: "direct-vs-reverse-acting", title: "7. Direct-Acting vs Reverse-Acting Control", file: "/legacy/docs/sections/07-direct-vs-reverse-acting.md" },
  { id: "integral-behavior", title: "8. Integral Behavior and Vendor Differences", file: "/legacy/docs/sections/08-integral-behavior-vendor-differences.md" },
  { id: "anti-windup", title: "9. Anti-Windup, Bumpless Transfer, and Mode Changes", file: "/legacy/docs/sections/09-anti-windup-bumpless-transfer.md" },
  { id: "tab-commissioning", title: "10. TAB & Commissioning Considerations", file: "/legacy/docs/sections/10-tab-commissioning-considerations.md" },
  { id: "tuning-methodologies", title: "11. PID Tuning Methodologies", file: "/legacy/docs/sections/11-pid-tuning-methodologies.md" },
  { id: "field-workflow", title: "12. Practical Field Tuning Workflow", file: "/legacy/docs/sections/12-field-tuning-workflow.md" },
  { id: "long-term-performance", title: "13. Long-Term Performance Evaluation", file: "/legacy/docs/sections/13-long-term-performance-evaluation.md" },
  { id: "pitfalls", title: "14. Common Pitfalls and Cautions", file: "/legacy/docs/sections/14-common-pitfalls-cautions.md" },
  { id: "walkthroughs", title: "15. Example Walkthroughs", file: "/legacy/docs/sections/15-example-walkthroughs.md" },
  { id: "checklist", title: "16. Final PID Tuning Checklist", file: "/legacy/docs/sections/16-final-pid-tuning-checklist.md" },
  { id: "datacenter-hvac-tuning", title: "17. Datacenter HVAC PID Tuning Guide", file: "/legacy/docs/sections/17-datacenter-hvac-tuning.md" },
  { id: "data-driven-tuning", title: "18. Data-Driven and Model-Based PID Tuning", file: "/legacy/docs/sections/18-data-driven-and-model-based-pid-tuning.md" },
  { id: "anti-overshoot-feedforward", title: "19. Anti-Overshoot, Feedforward, and Bumpless Logic", file: "/legacy/docs/sections/19-anti-overshoot-feedforward-and-bumpless-logic.md" },
  { id: "robotics-motion-notes", title: "20. Robotics and Motion-Control PID Notes", file: "/legacy/docs/sections/20-robotics-and-motion-control-pid-notes.md" },
  { id: "vendor-pid-technical-background", title: "21. Vendor PID Controller Technical Background", file: "/legacy/docs/sections/21-vendor-pid-controller-technical-background.md" },
  { id: "pid-troubleshooting-tree", title: "22. PID Tuning Troubleshooting Decision Tree", file: "/legacy/docs/sections/22-pid-tuning-troubleshooting-decision-tree.md" }
] as const;
