import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const root = process.cwd();
const lessonDirectory = join(root, "public", "legacy", "docs", "sections");
const helpDirectory = join(root, "public", "legacy", "help");
const outputFile = join(root, "src", "lib", "content", "generated-documentation.ts");

function readFiles(directory: string, extension: string) {
  return readdirSync(directory)
    .filter((fileName) => fileName.endsWith(extension))
    .sort()
    .map((fileName) => ({
      fileName,
      content: readFileSync(join(directory, fileName), "utf8")
    }));
}

const lessonMarkdown = Object.fromEntries(
  readFiles(lessonDirectory, ".md").map(({ fileName, content }) => [
    `/legacy/docs/sections/${basename(fileName)}`,
    content
  ])
);

const helpAssets = Object.fromEntries(
  readFiles(helpDirectory, ".svg").map(({ fileName, content }) => [
    `/legacy/help/${basename(fileName)}`,
    `data:image/svg+xml;base64,${Buffer.from(content).toString("base64")}`
  ])
);

const generatedSource = `// Generated by npm run docs:bundle. Do not edit by hand.
export const bundledLessonMarkdown: Record<string, string> = ${JSON.stringify(lessonMarkdown, null, 2)};

export const bundledHelpAssets: Record<string, string> = ${JSON.stringify(helpAssets, null, 2)};
`;

writeFileSync(outputFile, generatedSource, "utf8");
console.log(`Bundled ${Object.keys(lessonMarkdown).length} lessons and ${Object.keys(helpAssets).length} help assets.`);
