import type { ControllerConfig, ProcessModelDefinition, ProcessOptions } from "@/lib/sim/types";

type ModelSeed = Omit<ProcessModelDefinition, "span" | "processParams" | "defaultController" | "defaultOptions" | "analogDefaults"> & {
  processParams?: Partial<ProcessModelDefinition["processParams"]>;
  defaultController?: Partial<ControllerConfig>;
  defaultOptions?: Partial<ProcessOptions>;
};

function buildModel(config: ModelSeed): ProcessModelDefinition {
  const span = config.displayMax - config.displayMin;
  const processParams = {
    responseType: "selfRegulating" as const,
    gain: 1,
    lag1: 20,
    lag2: 0,
    deadTime: 0,
    leakage: 0.05,
    baseOutput: 40,
    outputMin: 0,
    outputMax: 100,
    interactionGain: 0,
    measurementLag: 0,
    ...config.processParams
  };

  const defaultController: ControllerConfig = {
    algorithm: "PI",
    form: "standard",
    kp: 1.6,
    ti: 20,
    td: 4,
    bias: processParams.baseOutput,
    pSource: "error",
    dSource: "pv",
    spFilterEnabled: false,
    spFilterTime: 8,
    pvFilterEnabled: false,
    pvFilterTime: 3,
    outputDeadband: 0,
    outputLimits: { min: processParams.outputMin, max: processParams.outputMax },
    mode: "auto",
    operatingMode: "single",
    manualOutput: processParams.baseOutput,
    cascadeGain: 0.6,
    feedforwardGain: 0.6,
    ...config.defaultController
  };

  const defaultOptions: ProcessOptions = {
    noiseLevel: 12,
    disturbanceProfile: "none",
    disturbanceIntensity: 20,
    showValveFeedback: false,
    valveDeadband: 0,
    valveStiction: 0,
    valveOvershoot: 0,
    flowCharacteristic: "linear",
    measurementLag: processParams.measurementLag ?? 0,
    backlash: 0,
    upsetProbability: 0,
    upsetMagnitude: 0,
    ...config.defaultOptions
  };

  return {
    ...config,
    precision: config.precision ?? 1,
    span,
    processParams,
    defaultController,
    defaultOptions,
    analogDefaults: {
      setpoint: { euMin: config.displayMin, euMax: config.displayMax, units: config.units },
      pv: { euMin: config.displayMin, euMax: config.displayMax, units: config.units },
      disturbance: { euMin: -100, euMax: 100, units: "% load" }
    }
  };
}

export const processModelRegistry: ProcessModelDefinition[] = [
  buildModel({
    id: "genericSingleLag",
    name: "Generic Deadtime + Single Lag",
    category: "Generic",
    units: "%",
    precision: 1,
    controllerDirection: "direct",
    summary: "A versatile first-order process for controller form comparisons.",
    description: "Single-lag self-regulating process with moderate deadtime and balanced gain.",
    displayMin: 0,
    displayMax: 100,
    initialPV: 44,
    initialSP: 56,
    processParams: { gain: 1.05, lag1: 22, deadTime: 5, baseOutput: 37 },
    defaultController: { kp: 1.8, ti: 24, td: 4 }
  }),
  buildModel({
    id: "genericDoubleLag",
    name: "Generic Deadtime + Double Lag",
    category: "Generic",
    units: "%",
    precision: 1,
    controllerDirection: "direct",
    summary: "Two-lag generic process that highlights sluggish recovery and derivative sensitivity.",
    description: "Second-order self-regulating model for damping and filtered setpoint behavior.",
    displayMin: 0,
    displayMax: 100,
    initialPV: 40,
    initialSP: 60,
    processParams: { gain: 0.92, lag1: 18, lag2: 24, deadTime: 7, baseOutput: 34 },
    defaultController: { kp: 1.5, ti: 30, td: 5 }
  }),
  buildModel({
    id: "liquidFlow",
    name: "Liquid Flow",
    category: "Flow",
    units: "gpm",
    precision: 1,
    controllerDirection: "direct",
    summary: "Fast liquid-flow loop with high sensitivity to valve nonlinearity.",
    description: "Flow process that responds quickly to valve movement and exposes derivative noise sensitivity.",
    displayMin: 0,
    displayMax: 120,
    initialPV: 46,
    initialSP: 64,
    processParams: { gain: 1.35, lag1: 6, deadTime: 1.2, baseOutput: 36 },
    defaultController: { kp: 1.15, ti: 10, td: 1.4 }
  }),
  buildModel({
    id: "airFlow",
    name: "Gas / Air Flow",
    category: "Flow",
    units: "cfm",
    precision: 0,
    controllerDirection: "direct",
    summary: "Airflow loop with rapid process movement and visible response to damper defects.",
    description: "Fast gas-flow style response that is useful for setpoint filtering and P action placement.",
    displayMin: 0,
    displayMax: 2200,
    initialPV: 920,
    initialSP: 1200,
    processParams: { gain: 1.28, lag1: 5, lag2: 2.5, deadTime: 1.6, baseOutput: 34 },
    defaultController: { kp: 0.95, ti: 12, td: 1.8 }
  }),
  buildModel({
    id: "liquidPressure",
    name: "Liquid Pressure",
    category: "Pressure",
    units: "psi",
    precision: 1,
    controllerDirection: "direct",
    summary: "Pressurized liquid system with a quick response and moderate disturbance coupling.",
    description: "Pressure loop that responds faster than temperature but slower than pure flow service.",
    displayMin: 0,
    displayMax: 120,
    initialPV: 58,
    initialSP: 72,
    processParams: { gain: 1.1, lag1: 10, lag2: 3, deadTime: 1.8, baseOutput: 40 },
    defaultController: { kp: 1.25, ti: 14, td: 2.4 }
  }),
  buildModel({
    id: "gasPressure",
    name: "Gas / Duct Pressure",
    category: "Pressure",
    units: "in. w.c.",
    precision: 2,
    controllerDirection: "direct",
    summary: "Fast pressure loop that makes chatter and disturbance rejection visible.",
    description: "Pressure loop that clearly reveals output chatter when PV filtering is disabled.",
    displayMin: 0,
    displayMax: 6,
    initialPV: 2.18,
    initialSP: 3.1,
    processParams: { gain: 1.22, lag1: 8, lag2: 2.4, deadTime: 1.5, baseOutput: 44 },
    defaultController: { kp: 1.35, ti: 12, td: 1.6 }
  }),
  buildModel({
    id: "pumpDifferentialPressure",
    name: "Pump Differential Pressure",
    category: "Pressure",
    units: "psid",
    precision: 1,
    controllerDirection: "direct",
    summary: "Remote differential pressure style loop with moderate lag and useful PI/PID comparisons.",
    description: "Hydraulic differential-pressure model with moderate deadtime and realistic pump-loop behavior.",
    displayMin: 0,
    displayMax: 30,
    initialPV: 10.8,
    initialSP: 15,
    processParams: { gain: 0.96, lag1: 16, lag2: 4, deadTime: 2.8, baseOutput: 46, outputMin: 20 },
    defaultController: { kp: 1.4, ti: 20, td: 2.2 }
  }),
  buildModel({
    id: "fanStaticPressure",
    name: "Fan Static Pressure",
    category: "Pressure",
    units: "in. w.c.",
    precision: 2,
    controllerDirection: "direct",
    summary: "Fast fan-static loop with strong visibility into output hunting.",
    description: "Fast airflow loop that reveals the value of smoothing, deadband, and PV filtering.",
    displayMin: 0,
    displayMax: 3,
    initialPV: 1.46,
    initialSP: 2.05,
    processParams: { gain: 1.16, lag1: 9, lag2: 1.8, deadTime: 1.2, baseOutput: 42, outputMin: 18 },
    defaultController: { kp: 1.55, ti: 10, td: 1.4 }
  }),
  buildModel({
    id: "integratingLevel",
    name: "Integrating Liquid Level",
    category: "Level",
    units: "%",
    precision: 1,
    controllerDirection: "direct",
    summary: "Integrating tank-level behavior that emphasizes disturbance rejection.",
    description: "Integrator-dominant model with low natural self-correction and strong response to sustained disturbance.",
    displayMin: 0,
    displayMax: 100,
    initialPV: 48,
    initialSP: 50,
    processParams: { responseType: "integrating", gain: 0.42, lag1: 38, deadTime: 3.2, leakage: 0.015, baseOutput: 50 },
    defaultController: { kp: 0.95, ti: 34, td: 0.6 }
  }),
  buildModel({
    id: "selfRegulatingLevel",
    name: "Self-Regulating Tank Level",
    category: "Level",
    units: "%",
    precision: 1,
    controllerDirection: "direct",
    summary: "Level process with some natural balancing, useful for PI and PID comparison.",
    description: "Slower self-regulating level response with moderate deadtime and lower process gain than flow loops.",
    displayMin: 0,
    displayMax: 100,
    initialPV: 38,
    initialSP: 52,
    processParams: { gain: 0.74, lag1: 28, lag2: 10, deadTime: 3.8, baseOutput: 43 },
    defaultController: { kp: 1.05, ti: 28, td: 1.8 }
  }),
  buildModel({
    id: "heatingCoilTemperature",
    name: "Heating Coil Temperature",
    category: "Temperature",
    units: "deg F",
    precision: 1,
    controllerDirection: "direct",
    summary: "Slow thermal loop where overshoot carries real comfort consequences.",
    description: "Heating process with thermal lag, deadtime, and a strong benefit from setpoint filtering.",
    displayMin: 45,
    displayMax: 140,
    initialPV: 72,
    initialSP: 96,
    processParams: { gain: 0.88, lag1: 32, lag2: 16, deadTime: 8, baseOutput: 36 },
    defaultController: { kp: 1.1, ti: 36, td: 4.4 }
  }),
  buildModel({
    id: "coolingCoilTemperature",
    name: "Cooling Coil Temperature",
    category: "Temperature",
    units: "deg F",
    precision: 1,
    controllerDirection: "reverse",
    summary: "Classic cooling-valve loop where correct direction is essential.",
    description: "Thermal cooling process with noticeable storage, deadtime, and moderate sensitivity to valve defects.",
    displayMin: 40,
    displayMax: 70,
    initialPV: 62,
    initialSP: 55,
    processParams: { gain: 0.98, lag1: 34, lag2: 15, deadTime: 7, baseOutput: 38 },
    defaultController: { kp: 1.25, ti: 34, td: 4.2 }
  }),
  buildModel({
    id: "heatExchangerTemperature",
    name: "Heat-Exchanger Outlet Temperature",
    category: "Temperature",
    units: "deg F",
    precision: 1,
    controllerDirection: "direct",
    summary: "Thermal exchanger process with slower output-to-PV coupling and smoother contribution profile.",
    description: "Moderately slow temperature process used for tuning comparisons around derivative damping.",
    displayMin: 60,
    displayMax: 180,
    initialPV: 118,
    initialSP: 132,
    processParams: { gain: 0.84, lag1: 28, lag2: 18, deadTime: 6.4, baseOutput: 41 },
    defaultController: { kp: 1.05, ti: 32, td: 3.8 }
  }),
  buildModel({
    id: "mixedAirTemperature",
    name: "Mixed-Air / Discharge-Air Temperature",
    category: "Temperature",
    units: "deg F",
    precision: 1,
    controllerDirection: "direct",
    summary: "Discharge-air style loop useful for setpoint steps, disturbances, and filter effects.",
    description: "Moderate-speed air-temperature process with dual-lag behavior and output saturation visibility.",
    displayMin: 45,
    displayMax: 95,
    initialPV: 58,
    initialSP: 62,
    processParams: { gain: 0.9, lag1: 18, lag2: 10, deadTime: 4.8, baseOutput: 40 },
    defaultController: { kp: 1.2, ti: 20, td: 2.8 }
  }),
  buildModel({
    id: "humidityMoisture",
    name: "Humidity / Moisture",
    category: "Humidity",
    units: "%RH",
    precision: 1,
    controllerDirection: "direct",
    summary: "Slow humidity loop where noise, filtering, and derivative choices are easy to compare.",
    description: "Very slow moisture-control process with long lags and a strong preference for measured tuning changes.",
    displayMin: 20,
    displayMax: 70,
    initialPV: 39,
    initialSP: 45,
    processParams: { gain: 0.76, lag1: 42, lag2: 20, deadTime: 9.5, baseOutput: 42 },
    defaultController: { kp: 0.95, ti: 40, td: 1.4 }
  }),
  buildModel({
    id: "motorSpeed",
    name: "Motor Speed",
    category: "Motion",
    units: "rpm",
    precision: 0,
    controllerDirection: "direct",
    summary: "Fast speed loop for VFD-style training with moderate load interaction.",
    description: "Motor speed response with quick correction, measurable disturbance sensitivity, and low deadtime.",
    displayMin: 0,
    displayMax: 1800,
    initialPV: 920,
    initialSP: 1200,
    processParams: { gain: 1.18, lag1: 4, lag2: 1.2, deadTime: 0.8, baseOutput: 48 },
    defaultController: { kp: 0.9, ti: 7, td: 0.8 }
  }),
  buildModel({
    id: "conveyorSpeed",
    name: "Conveyor Speed",
    category: "Motion",
    units: "ft/min",
    precision: 1,
    controllerDirection: "direct",
    summary: "A motion loop that highlights backlash, speed sag, and moderate deadtime.",
    description: "Conveyor speed control problem with a little storage and clear response to load upsets.",
    displayMin: 0,
    displayMax: 500,
    initialPV: 180,
    initialSP: 240,
    processParams: { gain: 1.02, lag1: 7, lag2: 2, deadTime: 1.4, baseOutput: 44 },
    defaultController: { kp: 1.05, ti: 11, td: 1.1 },
    defaultOptions: { backlash: 2.5 }
  }),
  buildModel({
    id: "neutralizationPh",
    name: "Neutralization pH",
    category: "Chemistry",
    units: "pH",
    precision: 2,
    controllerDirection: "direct",
    summary: "A nonlinear-feeling neutralization loop that rewards conservative tuning.",
    description: "Chemistry training model with high apparent gain near target and long settling behavior.",
    displayMin: 0,
    displayMax: 14,
    initialPV: 5.8,
    initialSP: 7,
    processParams: { gain: 0.68, lag1: 30, lag2: 18, deadTime: 10, baseOutput: 46, measurementLag: 3 },
    defaultController: { kp: 0.7, ti: 38, td: 0.9 },
    defaultOptions: { measurementLag: 3, noiseLevel: 10 }
  }),
  buildModel({
    id: "reactorTemperature",
    name: "Reactor Temperature",
    category: "Reactor",
    units: "deg C",
    precision: 1,
    controllerDirection: "direct",
    summary: "A stored-energy thermal process where overshoot and saturation risk matter.",
    description: "Reactor temperature model with long lag, moderate deadtime, and strong disturbance sensitivity.",
    displayMin: 25,
    displayMax: 240,
    initialPV: 110,
    initialSP: 135,
    processParams: { gain: 0.8, lag1: 40, lag2: 24, deadTime: 11, baseOutput: 38 },
    defaultController: { kp: 0.88, ti: 44, td: 4.8 }
  }),
  buildModel({
    id: "distillationColumn",
    name: "Distillation Column Section",
    category: "Separation",
    units: "% purity",
    precision: 1,
    controllerDirection: "direct",
    summary: "Dead-time-dominant process for showing why blind aggressive pushing fails.",
    description: "Column section response with long transport delay and sluggish stored-energy behavior.",
    displayMin: 70,
    displayMax: 100,
    initialPV: 84,
    initialSP: 89,
    processParams: { gain: 0.62, lag1: 50, lag2: 24, deadTime: 18, baseOutput: 52 },
    defaultController: { kp: 0.74, ti: 60, td: 5.5 }
  })
];

export const processModelMap = Object.fromEntries(processModelRegistry.map((model) => [model.id, model]));

export function getProcessModel(modelId: string) {
  return processModelMap[modelId] ?? processModelRegistry[0];
}
